[connection]
# remote websocket endpoint
remote = "ws://127.0.0.1:8080"
# name for this instance
name = "debug-client"
# retry times before give up
retry = 10
# the key used in SHA256-HMAC authentication
key = "keyusedforhmac"
# retry interval
retry-interval = 10

# Set corresponding item to false if you don't want to enable some test
[api]
resolve = true
ping = true
tcping = true
mtr = true
speed = true
